### ISSUE TITLE
Payment options visible after approved

### ISSUE THREAD

**Issue by bkcsoft** [SiimKirjanen/seatreg#197]
The payment options are still visible are the booking has been approved, which could be a bit confusing to customers.
Not sure if there's a reason they're still visible, but having an option to hide payment stuff when approved would be nice.
Screenshot because a picture says more than a thousand words.
![image](https://github.com/SiimKirjanen/seatreg/assets/4726179/b56bb5df-843c-4383-bd5e-22dec20a289b)

**Comment by SiimKirjanen** [comment]
Hello
Thank you for notifying,
When using payment method as Stripe or PayPal then those payment options will not show after successful payment. 
When manually approving bookings (with booking manager) then yes those payment options will be still showing. Its by design as some don't use pending bookings at all (in setting you can configure it to make new bookings approved be default). 
But I like the idea of having option to hide them. I think I will implement feature to set payment completed in booking manager so its possible to hide those options when using custom payments.

**Comment by bkcsoft** [comment]
Now that i understand better how it works, it seems like the better fix would be the ability to manually mark a booking as payed in the bookings manager. In short: if there are payment options, show a button in the Booking Manager that runs [SeatregPaymentSevice::insertOrUpdate](https://github.com/SiimKirjanen/seatreg/blob/bfa55e86b81f9bbdc565975e1e5c5b1c9192f8a3/php/services/SeatregPaymentService.php#L32).
In our case we use custom payments for invoices, so we do wanna make sure they've actually been payed :smile: 

Would you be fine with me sending a PR for this?

**Comment by bkcsoft** [comment]
I just noticed that what I proposed above has already been suggested in https://wordpress.org/support/topic/alternative-payment-method-manual-payment/
> where the payment can be manually marked as received

**Comment by SiimKirjanen** [comment]
Yes you can make a PR. 
It would be nice if admin can toggle between payment completed and not completed.
This action should be logged in payment logs. So we could see who made it.
Also I think this toggle functionality should use Ajax.

**Comment by SiimKirjanen** [comment]
I will start developing this feature
